"""add location_id to users

Revision ID: 643b82d33fd9
Revises: 3a3d6d1227a2
Create Date: 2025-12-12 10:11:41.659504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643b82d33fd9'
down_revision: Union[str, Sequence[str], None] = '3a3d6d1227a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    # ### end Alembic commands ###
